server:
  port: 8090

---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mark.camp715@gmail.com
    password: Macdev04
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true