server:
  port: 8090

---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: #######@gmail.com
    password: ######
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
